version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: admin2411
      POSTGRES_DB: challenge_db
    ports:
      - "5432:5432"
    volumes:
      - /postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "8000:8000"
    volumes:
      - /app_data:/app
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

  trigger:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trigger
    volumes:
      - /app_data:/app
    command: ["python", "trigger/trigger.py"]

volumes:
  postgres_data:
  app_data: